version: "3.3"

services:
  backend:
    build: ./backend
    command: npm run dev
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/app
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
